### ISSUE TITLE
New Rollbar Integration

### ISSUE THREAD

**Issue by chazhenry** [rollbar/rollbar-java#100]
New to rollbar and trying to integrate in Android Studio for Android app. Doc is a mess of old and new. Main page references 0.2.0, but 1.0.0 is referenced later. Is there a guide for integration and catching uncaught errors from scratch with 1.0 without all of the upgrade noise?

I've put 
  * compile('com.rollbar:rollbar-java:1.0.0') in my build.gradle, 
   * access token in AndroidManifest.xml
   * Rollbar.init(this); 
   * import com.rollbar.android.Rollbar;
in MainActivity 
but still, I cannot resolve the Rollbar symbol.

**Comment by rivkahstandig3636** [comment]
Hi @chazhenry, Sorry the docs are so confusing :( We're working on updating them this week to be less confusing!

Have you checked out the rollbar-android example [here](https://github.com/rollbar/rollbar-java/tree/master/examples/rollbar-android)? I think it will be the most helpful for getting started right now.

**Comment by Robarelli** [comment]
The referenced link to examples seem to be for the deprecated versions and not 1.0.0. Is there anything that is more up to date?

**Comment by romsrini** [comment]
The docs say to use import rollbar-java via gradle but the example code linked above refers to a rollbar.android package which doesn't even exist in the latest library. So there isn't anything helpful to get started right now. Its currently March 14 and you said you would be updating the docs the week of February 6th. We are a paying client so we'd like to get this resolved as soon as possible.

**Comment by Robarelli** [comment]
What solved it for me for Android was including the aar package as well. So the dependencies would be:
```
implementation 'com.rollbar:rollbar-android:1.0.0'
implementation 'com.rollbar:rollbar-android:1.0.0@aar'
```

**Comment by rokob** [comment]
The example at https://github.com/rollbar/rollbar-java/tree/master/examples/rollbar-android is for the 1.0.0 version of things. The build.gradle file there is referencing the within project dependency of rollbar-android, but that translates to the compile dependency of `com.rollbar:rollbar-android:1.0.0`, and also due to the transitive dependencies issues with aars also `com.rollbar:rollbar-android:1.0.0@aar`.

The docs state the different packages that exist. What you need to depend on depends on what you are building. For android, you need to depend on the android package.

**Comment by romsrini** [comment]
Thank you @Robarelli !

@rokob , I think you should add what Robarelli said to https://rollbar.com/docs/notifier/rollbar-java/#android

That page currently indicates using the following:
compile('com.rollbar:rollbar-java:1.0.0')

And that just isn't going to work for Android.

**Comment by rokob** [comment]
👍 I will add some things to the docs, I just had another look at them and agree they are definitely lacking for Android.

**Comment by przemeknzb** [comment]
Docs updated yet?

**Comment by rivkahstandig3636** [comment]
@rokob Were you able to add some docs?

**Comment by gpedro** [comment]
same issue here:
```gradle
// app/build
compile "com.rollbar:rollbar-android:${rootProject.ext.rollbarVersion}@aar"
compile "com.rollbar:rollbar-java:${rootProject.ext.rollbarVersion}"
```

<img width="593" alt="captura de tela 2018-08-02 as 18 11 48" src="https://user-images.githubusercontent.com/2898638/43613975-92585ace-967f-11e8-856a-652113ab1f93.png">

**Comment by gpedro** [comment]
:FUCKYEA:

solution:
```gradle
// app/build.gradle
compile ("com.rollbar:rollbar-android:${rootProject.ext.rollbarVersion}@aar") {
}
compile "com.rollbar:rollbar-java:${rootProject.ext.rollbarVersion}"
```

**Comment by gpedro** [comment]
:fuckyea:

solved with transitive flag
```gradle
// app/build.gradle
    compile ("com.rollbar:rollbar-android:${rootProject.ext.rollbarVersion}@aar"){
        transitive = true
    }
compile "com.rollbar:rollbar-java:${rootProject.ext.rollbarVersion}"
```

> An artifact only notation creates a module dependency which downloads only the artifact file with the specified extension. Existing module descriptors are ignored.
https://stackoverflow.com/a/31753839
