### ISSUE TITLE
Batch payload sending

### ISSUE THREAD

**Issue by latos** [rollbar/rollbar-java#103]
The API does not support batching.  The API should add support for batched requests (I don't know if there's a public ticket system for the rollbar API) - but once that's done the client should add support for it as well (and buffering with a pool + batching should be enabled by default)

See also https://github.com/rollbar/rollbar-java/issues/30

**Comment by jessewgibbs** [comment]
Per discussion in https://github.com/rollbar/rollbar-java/issues/30, we've decide to no longer support batch sending in our SDKs, with the exception of the `BufferedSender` feature.
