### ISSUE TITLE
Trace + Trace Chain missing Raw key

### ISSUE THREAD

**Issue by ajtran** [rollbar/rollbar-java#108]
So i was stepping around in the proguard code and i was wondering if i was overlooking something. Im trying to help a user debug their issue:

[internal] https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/488687/conversations/15168176927

When i walk through the code with this raw item: 39192805869, i get stuck at this line of the code: https://github.com/rollbar/mox/blob/master/mox/lib/proguard.py#L193

In this case, the trace doesn’t have a `raw` key. and i’ve checked the data format of payloads from the api docs and neither `trace` nor `trace_chain` have the `raw` key either. So, i was wondering if i was missing something?

**Comment by rokob** [comment]
The raw key gets added by the backend processing pipeline. The entire content of this issue is non-public links and isn't really useful here as there isn't anything related to the notifier. This is a backend issue.
