### ISSUE TITLE
 No errors reported after Crash

### ISSUE THREAD

**Issue by ajtran** [rollbar/rollbar-java#110]
User is trying to set up Rollbar-Java and is able to get general errors, but unable to get errors reported after a crash. With the newest release, this should be done automatically.

User has below in gradle:
```
api('com.rollbar:rollbar-java:1.0.0')
```

internal: https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/849049/conversations/15129836962

**Comment by rokob** [comment]
This is for Android, so they should include the Android part of this library and use the Android specific interface. For an example of an Android usage see https://github.com/rollbar/rollbar-java/blob/master/examples/rollbar-android/src/main/java/com/rollbar/example/android/MainActivity.java and the gradle dependencies should be:

```
dependencies {
    compile 'com.rollbar:rollbar-java:1.0.0'
    compile 'com.rollbar:rollbar-android:1.0.0@aar'
}
```
