### ISSUE TITLE
Allow Rollbar to be disabled ( e.g. in local development environments ) 

### ISSUE THREAD

**Issue by mikebocian** [rollbar/rollbar-java#112]
I would like to have this option: 
https://github.com/rollbar/rollbar-gem/blob/ffd4278332cc63b6dc29cde5fc3716793c455bec/lib/rollbar/configuration.rb#L19
available also in java plugin. 

Currently, there is no way to configure rollbar to be in "dryRun" mode. It is especially necessary in local development. Currently we need to specify some random rollbar access key like: "test" "local". It's not beautiful, especially when your servers replying with error that token is not valid. Also we generate load, which is completely dump.

We could however mock Rollbar here, but I personally don't want to have Mockito or JMock on my production classpath.

Regards
Mike.

**Comment by basoko** [comment]
Hi @mikebocian,

One possible workaround until it's added could be to implement a custom [filter](https://github.com/rollbar/rollbar-java/blob/master/rollbar-java/src/main/java/com/rollbar/notifier/filter/Filter.java#L30) that checks the `Data.environment` content and decide if the data should be filtered, that should result in not sending the payload.

Thanks!

**Comment by mikebocian** [comment]
Looks promising. I will change my code to filter requests instead of pushing with wrong token.

But it is not that great as it could be with `enabled` option :)
