### ISSUE TITLE
Crash on Android devices with API version lower than 19

### ISSUE THREAD

**Issue by jsjem** [rollbar/rollbar-java#115]
The next line causes crash during rollbar initialization:
https://github.com/rollbar/rollbar-java/blob/f95c18e9406c3229adb4c22a29d51084b3ed8da8/rollbar-java/src/main/java/com/rollbar/notifier/sender/SyncSender.java#L25

This happens due to the class `StandardCharsets` does not exists in the Android 4.3 and lower.

**Comment by rivkahstandig3636** [comment]
Thanks for the bug report!
