### ISSUE TITLE
Make an async sender the default

### ISSUE THREAD

**Issue by rokob** [rollbar/rollbar-java#117]
- Use one of the queue based senders as the default sender instead of the current sync sender
- Document that the default is async and what the queueing strategy is
- Document how to replace the queue and the whole sender

**Comment by ericluria** [comment]
Is there an example anywhere of how to use the async senders?

**Comment by basoko** [comment]
Hi @ericluria 

You can find an example of how to use it here https://github.com/rollbar/rollbar-java/blob/master/rollbar-android/src/main/java/com/rollbar/android/Rollbar.java#L233. The android implementation requires to use a queue persisted to disk, but by default it uses a `ConcurrentLinkedQueue`.

BTW we are planning to setting by default the buffered sender.

**Comment by ericluria** [comment]
Thanks, @basoko! Didn't realize the change was going to be made so quickly.
