### ISSUE TITLE
Not able to get device/OS information with Android apps.

### ISSUE THREAD

**Issue by RollbarExample** [rollbar/rollbar-java#128]
Hi,
Is it possible to get the device and OS details with the Android notifier?

Thanks.
Wahid

**Comment by rivkahstandig3636** [comment]
Hi Wahid, Yes, it is possible. Can you send your config?

**Comment by RollbarExample** [comment]
Sure, Here are the details.

Manifest file

**Comment by rokob** [comment]
Android by default collects device information: https://github.com/rollbar/rollbar-java/blob/master/rollbar-android/src/main/java/com/rollbar/android/provider/ClientProvider.java#L52,L81 https://github.com/rollbar/rollbar-java/blob/master/rollbar-android/src/main/java/com/rollbar/android/Rollbar.java#L234,L239

Are you getting items but without device info or are you getting no items?
