### ISSUE TITLE
android module

### ISSUE THREAD

**Issue by Crisfole** [rollbar/rollbar-java#14]
Pull in [rollbar-android](https://github.com/rollbar/rollbar-android) as a submodule. Make it depend on the other modules to make the interface consistent.

**Comment by aistomin** [comment]
@Crisfole I would be glad to help there, but the problem is that I'm not really sure what does "Pull in rollbar-android as a submodule.". Should source code be just copied or rollbar-android should be ataached as git-submodule to rollbar-java?
