### ISSUE TITLE
Configuration of RollbarAppender

### ISSUE THREAD

**Issue by jrogers** [rollbar/rollbar-java#145]
While the rollbar-logback module is a nice addition, it isn't very configurable and as a result isn't very useful for larger projects/applications.

It would be very useful to allow it to be passed a Config object or already created Rollbar instance. This would allow setting things like Providers on it, as well as the environment and other context settings.

Currently when logback calls start on the RollbarAppender, it always creates a brand new Rollbar instance. The only customizable thing is the accessToken.

**Comment by rokob** [comment]
Does the just merged PR https://github.com/rollbar/rollbar-java/pull/143 address your concerns? It makes it possible to configure things much more flexibly.

**Comment by jrogers** [comment]
Yeah it should work for my use case. I probably wouldn't have made the ConfigProvider a string class name, but rather an actual object or a class reference.

**Comment by jrogers** [comment]
Thanks for getting this into the release!
