### ISSUE TITLE
Page translator

### ISSUE THREAD

**Issue by Tiodoro** [rollbar/rollbar-java#148]
Hello, i have detect somo issues on translator for spanish, at least is theone i understan, may some one help me, because im not pretty sure about how to fix it, actually it is not mine but i was going tru it and i want to know the process to help in those cases, or what can or should i do in this situation,thanks for your support. here is the link, is on the area that mean policias, should be politicas, and theres someting kind of weird to me, but you are the expert, it begins with( https://www).
Regards.

.zendesk.com/company/policies-procedures/

**Comment by rivkahstandig3636** [comment]
Hi there, I think you posted this in the incorrect repo.

**Comment by Tiodoro** [comment]
sorry, my bad!
