### ISSUE TITLE
Spring controller advice jar

### ISSUE THREAD

**Issue by berlin-ab** [rollbar/rollbar-java#15]
It would be nice to be able to do something like:

compile("com.rollbar:rollbar-spring:x.x.x")

and be able to not have to configure the `@ControllerAdvice`.  Better yet, it would be nice to have the library using Spring Boot Autoconfiguration so that the user of the library would only be responsible for setting properties.

**Comment by Crisfole** [comment]
Hey, Great idea! PRs on this are welcome. This is exactly what I was imagining we'd wind up doing: targeted, small modules for each library integration.

Feel like giving it a stab?

**Comment by iamareebjamal** [comment]
Any reason this was closed? Currently sentry provides very easy mechanism to integrate with Spring. You don't have to add even a little bit of code. Just some logger level patching is required, that too if you want custom levels to be logged
