### ISSUE TITLE
Rollbar-Log4J Additional Docs

### ISSUE THREAD

**Issue by ajtran** [rollbar/rollbar-java#150]
internal: https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/849049/conversations/17224559673

Could we verify this, so the docs can be updated properly?

When setting up rollbar-log4j java integration in a project which builds a fat-jar, additional configuration is needed, which is not mentioned in the docs or example. As rollbar-log4j contains additional .dat files, these must to be concatenated with the other log4j files.

This can be achieved using this gradle lib https://github.com/TheBoegl/shadow-log4j-transformer
This is the maven equivalent: https://github.com/edwgiz/maven-shaded-log4j-transformer (however, I only used the gradle solution so far)

This issue contains additional information, the logged error, as well as the links to the libraries https://issues.apache.org/jira/browse/LOG4J2-954 Might be worth adding this to the rollbar doc, as the logged error is a little misleading.

**Comment by st-h** [comment]
Hey there. I initially submitted this issue via the official communication channels. Just wanted to let you know that, if you have any questions or need any help, please feel free to ping me.

**Comment by basoko** [comment]
Hi Steve, 

Thanks for reporting this! I updated the documentation so it reflects the solutions you commented here. You can check them here https://docs.rollbar.com/docs/log4j2
