### ISSUE TITLE
'View Release Notes' links to deprecated rollbar-android library

### ISSUE THREAD

**Issue by petitJAM** [rollbar/rollbar-java#165]
![image](https://user-images.githubusercontent.com/1505760/44349109-da891500-a461-11e8-9d7c-d34d6465d318.png)

This links to the old Android library: https://github.com/rollbar/rollbar-android

Not sure where to post bugs for the main site, so I'm doing it here.

**Comment by jessewgibbs** [comment]
This is a bug in the Rollbar app, so I'm going to close this issue and create one in our internal tracker.
