### ISSUE TITLE
Use nonblocking IO (and a more capable HTTP client)

### ISSUE THREAD

**Issue by marshallpierce** [rollbar/rollbar-java#17]
Currently, sending a throwable report is blocking, and uses the basic built-in HttpURLConnection client from the JDK. This means that reporting a throwable in the natural way during request handling will delay service time unless users go to the trouble of wrapping Rollbar in an abstraction that allows them to hand off invocations to another thread. While that's possible, it would make the life of all users a lot easier if they could rely on the Rollbar client using nonblocking i/o so they could "fire and forget" requests.

This would also be a natural opportunity to use a more full-featured http client like https://github.com/AsyncHttpClient/async-http-client or https://hc.apache.org/httpcomponents-asyncclient-dev/index.html. The built-in client is very limited in its configurability.

If this is of interest, I'm happy to contribute a PR.

**Comment by Crisfole** [comment]
We're very happy to accept PRs for added modules that do this. We want the core modules to *not* depend on external dependencies so people can pick ones that match their existing infrastructure.

For this it should be simple: just implement the `Sender` class from the rollbar-sender module.  The Rollbar class uses the callback version under the hood: https://github.com/rollbar/rollbar-java/blob/master/rollbar-sender/src/main/java/com/rollbar/sender/Sender.java#L16-L21

For the other method (https://github.com/rollbar/rollbar-java/blob/master/rollbar-sender/src/main/java/com/rollbar/sender/Sender.java#L10-L14) I think it's appropriate to create an additional RollbarResponseCode for 'SentAwaitingResponse'  (or some better name).

**Comment by marshallpierce** [comment]
Closing per comments in #21
