### ISSUE TITLE
Does rollbar java support code context?

### ISSUE THREAD

**Issue by RollbarExample** [rollbar/rollbar-java#170]
Hi,
Does rollbar java support code context? I was trying to integrate by following https://docs.rollbar.com/docs/code-context but does not appear github link on error item page. Here is my configuration code and error item page screenshot.
```
Config config = ConfigBuilder.withAccessToken("ff70890763f540d4819dd0fb1d9d5e40")
				.environment("production")
				.server(new Provider<Server>() {

					@Override
					public Server provide() {
						return new Server.Builder().branch("master")
								.root("/")
								.codeVersion("844b973")
						        .build();
					}
				})
				.build();		
		rollbar = new Rollbar(config);
		rollbar.init(config);
```
![rollbar-java-code-context](https://user-images.githubusercontent.com/32199575/50385607-5a6c0800-06fe-11e9-9ce6-204cdaf6a379.PNG)

Repository Link:
https://github.com/RollbarExample/Spring-Example

Rollbar project link:
https://rollbar.com/RollbarExample/Rollbar-Java-Example/items/280/

Thanks,
Wahid Ali.

**Comment by jessewgibbs** [comment]
Hey Wahid,

Do you mind re-submitting this to support@rollbar.com and let the team know that you're working with Jason?  Thanks!
