### ISSUE TITLE
Not capturing local variables.

### ISSUE THREAD

**Issue by RollbarExample** [rollbar/rollbar-java#171]
Hey, 

I was updated latest rollbar ie v1.4.0 in my project to get support of local variables. But it does not seem to work. Here is the details.

**pom**
```
<dependency>
    <groupId>com.rollbar</groupId>
    <artifactId>rollbar-web</artifactId>
    <version>1.4.0</version>
    <type>pom</type>
</dependency>
```
**Configuration code :**
```
Config config = ConfigBuilder.withAccessToken("ff70890763f540d4819dd0fb1d9d5e40")
				.environment("production").enabled(true)
				.server(new Provider<Server>() {

					@Override
					public Server provide() {
						return new Server.Builder().branch("master")
								.root("/")
								.codeVersion("844b973")
						        .build();
					}
				})
				.build();
		
		
		rollbar = new Rollbar(config);
		rollbar.init(config);
```
**Error item page screenshot**
![rollbar-java-code-context](https://user-images.githubusercontent.com/32199575/50385784-6907ee80-0701-11e9-8d8f-da5fafd2058d.PNG)

Please let me know if i am doing any thing wrong.

Thanks,
Wahid Ali.

**Comment by RollbarExample** [comment]
@rokob. i went through the instruction. Can you please tell me what is foo.jar in that.
```
java -jar foo.jar -agentpath:path/to/librollbar_java_agent.dylib
```
And also what it will be in case Rollbar?

Thanks,
Wahid Ali

**Comment by rokob** [comment]
It is an example name, it isn't a real file. It represents whatever jar you are trying to run.

**Comment by jessewgibbs** [comment]
Wahid I'm going to close this issue for now.

**Comment by RollbarExample** [comment]
Hey,

I am using rollbar-java with spring boot web project to capture local variable in stack trace, And the app i am deploying on tomcat server. I found some reference to add agent path in the tomcat under catelina.bat file. Here is the link https://stackoverflow.com/questions/7738794/add-jvm-options-in-tomcat
When i am deploying the app while adding agent path, getting below exception.
```
WEB-INF/lib/byte-buddy-1.9.3.jar] for annotations org.apache.tomcat.util.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19 at org.apache.tomcat.util.bcel.classfile.Constant.readConstant(Constant. java:97) at org.apache.tomcat.util.bcel.classfile.ConstantPool.<init>(ConstantPoo l.java:54)
```
Here is the tomcat catelina.bat file detail.
```
:doStart
shift
if "%TITLE%" == "" set TITLE=Tomcat
set _EXECJAVA=start "%TITLE%" %_RUNJAVA%
if not ""%1"" == ""-security"" goto execCmd
shift
echo Using Security Manager
set "SECURITY_POLICY_FILE=%CATALINA_BASE%\conf\catalina.policy"
goto execCmd

:doStop
shift
set ACTION=stop
set CATALINA_OPTS=-agentpath:F:\apache-tomcat-8.5.4\librollbar_java_agent.dylib
goto execCmd

:doConfigTest
shift
set ACTION=configtest
set CATALINA_OPTS=-agentpath:F:\apache-tomcat-8.5.4\librollbar_java_agent.dylib
goto execCmd
```
Can you help me out? or suggest me if i am doing any thing wrong.

Thanks,

Wahid Ali.

**Comment by rokob** [comment]
It looks like you are using Windows. A `.dylib` is a MacOS dynamic library, you cannot use it on Windows. We also distribute the `.so` for Linux, but you will need to use Rust to build your own `.dll` for Windows.
