### ISSUE TITLE
Android data is sent but doesn't appear on Rollbar

### ISSUE THREAD

**Issue by dieg0** [rollbar/rollbar-java#172]
Hi, we have a Kotlin Android app, we want to integrate rollbar but so far it hasn't worked, our gradle fie:

```
android {
    compileSdkVersion 26
    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    //noinspection GradleCompatible
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.android.support:design:26.1.0'
    implementation 'com.basecamp:turbolinks:1.0.8'
    implementation 'com.rollbar:rollbar-java:1.4.0'
}
```
Lines from Main Activity:

```
import com.rollbar.notifier.Rollbar
import com.rollbar.notifier.config.ConfigBuilder

class MainActivity : AppCompatActivity(), NavigationView.OnNavigationItemSelectedListener {
    lateinit private var turbolinksHelper: TurbolinksHelper

    val config = ConfigBuilder.withAccessToken("f9178dca7b5d450b986b36ddc8b2159a")
        .language("scala")
        .codeVersion("1.0.0")
        .environment("production")
        .enabled(true)
        .build()
    val rollbar = Rollbar.init(config)

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        rollbar.info("This is a test message")
        rollbar.log(Error("this is an error"), "another thing to exist")
```
Using Charles I can see that the app is communicating with rollbar service, but nothing appears on the projects dashboard

Thanks in advance

**Comment by jessewgibbs** [comment]
Hi @dieg0,

Can you share the logs from Charles?  I'd like to see what HTTP response code is returned from the Rollbar API when your app makes a call to it.

**Comment by shaka0241** [comment]
![image](https://user-images.githubusercontent.com/25334358/51137064-c254d080-181c-11e9-9df8-81adcf3d069c.png)

![image](https://user-images.githubusercontent.com/25334358/51137137-ec0df780-181c-11e9-9d64-43fd14d7ab7d.png)

![image](https://user-images.githubusercontent.com/25334358/51137180-09db5c80-181d-11e9-9d89-acc925ac25ae.png)

![image](https://user-images.githubusercontent.com/25334358/51137200-165fb500-181d-11e9-91b8-c96701aaaa35.png)


Hi @jessewgibbs . This is my Charles log.

**Comment by jessewgibbs** [comment]
Can you export the full text content?

**Comment by shaka0241** [comment]
![image](https://user-images.githubusercontent.com/25334358/51138063-e9140680-181e-11e9-989b-08d2cf6d46d3.png)

![image](https://user-images.githubusercontent.com/25334358/51138112-0517a800-181f-11e9-951a-10baa31a5e73.png)

![image](https://user-images.githubusercontent.com/25334358/51138139-12cd2d80-181f-11e9-85c8-c66489075fc7.png)


MY XML FILE


<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE charles-session SYSTEM "https://www.charlesproxy.com/dtd/charles-session-1_2.dtd">

<charles-session>
<transaction status="COMPLETE" method="CONNECT" protocolVersion="HTTP/1.1" protocol="https" host="35.201.81.77" actualPort="443" remoteAddress="35.201.81.77/35.201.81.77" clientAddress="/192.168.100.54" clientPort="64775" startTime="2019-01-14T16:48:09.398-03:00" startTimeMillis="1547495289398" endTime="2019-01-14T16:52:10.539-03:00" endTimeMillis="1547495530539" duration="241141" dnsDuration="0" connectDuration="10" sslDuration="356" overallSpeed="94" totalSize="22816">
<ssl protocol="TLSv1.2" cipherSuite="TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256" />
<alpn protocol="http/1.1" />
<request handshake="1002" headers="0" body="2863">
<headers>
<first-line><![CDATA[CONNECT 35.201.81.77:443 HTTP/1.1]]></first-line></headers></request>
<response status="200" handshake="18085" headers="0" body="866">
<headers>
<first-line><![CDATA[HTTP/1.1 200 Connection established]]></first-line></headers></response></transaction></charles-session>

**Comment by shaka0241** [comment]
`<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE charles-session SYSTEM "https://www.charlesproxy.com/dtd/charles-session-1_2.dtd">

<charles-session>
<transaction status="COMPLETE" method="CONNECT" protocolVersion="HTTP/1.1" protocol="https" host="35.201.81.77" actualPort="443" remoteAddress="35.201.81.77/35.201.81.77" clientAddress="/192.168.100.54" clientPort="64775" startTime="2019-01-14T16:48:09.398-03:00" startTimeMillis="1547495289398" endTime="2019-01-14T16:52:10.539-03:00" endTimeMillis="1547495530539" duration="241141" dnsDuration="0" connectDuration="10" sslDuration="356" overallSpeed="94" totalSize="22816">
<ssl protocol="TLSv1.2" cipherSuite="TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256" />
<alpn protocol="http/1.1" />
<request handshake="1002" headers="0" body="2863">
<headers>
<first-line><![CDATA[CONNECT 35.201.81.77:443 HTTP/1.1]]></first-line></headers></request>
<response status="200" handshake="18085" headers="0" body="866">
<headers>
<first-line><![CDATA[HTTP/1.1 200 Connection established]]></first-line></headers></response></transaction></charles-session>`

**Comment by shaka0241** [comment]
![image](https://user-images.githubusercontent.com/25334358/51138299-88d19480-181f-11e9-9d3c-bce641b7dcc4.png)

@jessewgibbs

**Comment by jessewgibbs** [comment]
Hey there,

I think this is an issue with your local configuration.  Check out https://stackoverflow.com/questions/49117151/charles-proxy-ssl-ssl-proxying-not-enabled-for-this-host.  Can you try making that update in your local configuration and then see if it works?

**Comment by shaka0241** [comment]
``
<p>test ``

**Comment by shaka0241** [comment]
```
<p> test </p> ```

**Comment by shaka0241** [comment]
We configure charles correctly. Apparently the rollbar call is not being made. According to the documentation, it has been configured as follows:

Lines from Main Activity

```

**Comment by shaka0241** [comment]
I tried, but it does not keep showing me the call to rollbar.

```

   override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        Log.d("prueba consola","hola de nuevo")
        Log.d("prueba consola",rollbar.toString())
        rollbar.info("This is a test message")
        rollbar.log(Error("this is an error"), "another thing to exist")
        setContentView(R.layout.activity_main)
        turbolinksHelper = TurbolinksHelper(this, this, turbolinksView)
        turbolinksHelper.visit(getString(R.string.base_url), true)
        rollbar.close(true);
    }

**Comment by jessewgibbs** [comment]
@rokob any ideas about how to troubleshoot this further?

**Comment by shaka0241** [comment]
Please anyone has any idea how we can get this to work? We have instantiated rollbar and tried init, log, info and close methods from that object. Perhaps this isn't the right approach in Kotlin? Thanks in advance

**Comment by rokob** [comment]
Sorry for the lack of reply. I am going to make an app in Kotlin and see if I can dig into what is going on here. Everything you are doing appears correct, so I will see what I can find out playing with it myself.

**Comment by shaka0241** [comment]
> Sorry for the lack of reply. I am going to make an app in Kotlin and see if I can dig into what is going on here. Everything you are doing appears correct, so I will see what I can find out playing with it myself.

Thanks a lot!

**Comment by jtrinc** [comment]
Hi @rokob, has there been any progress here? I am having the same issue on a Kotlin Android app, I don't see any Rollbar activity in the network profiler.

**Comment by alif** [comment]
@dieg0 are you still unable to integrate rollbar?
We believe this works as expected and would like to confirm before closing this issue.

**Comment by dieg0** [comment]
No longer working on that project, no problem if you close the issue
