### ISSUE TITLE
Configure logcat metadata [Feature Request]

### ISSUE THREAD

**Issue by mauricegavin** [rollbar/rollbar-java#173]
We use the rollbar-java SDK in our Android app. One of the features that we find useful is the ability to attach a device's logcat output to crashes. However, the number of lines logged is capped at 100. In many cases the 100 lines preceeding the crash are consumed with stack traces and uninformative data.

We would like to have the choice to upload more than the current default of 100 lines. 

The relevant class in the SDK appears to be `com.rollbar.android.provider.ClientProvider`.

```
private ArrayList<String> getLogcatInfo() {
        ArrayList<String> log = null;
        int pid = android.os.Process.myPid();
        try {
            Process process = Runtime.getRuntime().exec("logcat -d");
            InputStreamReader isr = new InputStreamReader(process.getInputStream());
            BufferedReader br = new BufferedReader(isr, 8192);
            List<String> lines = new ArrayList<>();
            String line;
            while ((line = br.readLine()) != null) {
                if (line.contains(String.valueOf(pid))) {
                    lines.add(line);
                    if (lines.size() > MAX_LOGCAT_SIZE) {
                        lines.remove(0);
                    }
                }
            }
            log = new ArrayList<>(lines);
        } catch (IOException e) {
            Log.e(Rollbar.TAG, "Unable to collect logcat info.", e);
        }
        return log;
    }
```

Is it possible for us to increase MAX_LOGCAT_SIZE (and potentially the buffer) so that we can export more of the logcat output?

**Comment by jessewgibbs** [comment]
@rokob what do you think?  Could they fork rollbar-java, increase the amount of log data captured, and still have things work correctly after sending to our API?

**Comment by rokob** [comment]
1. Before we make a change, this is possible without forking the library. You can use a `ConfigProvider` which can be passed to the `Rollbar` constructor. That provider can use your own custom client provider which can handle logcat however you want.
2. We can provide a configuration option to set the max logcat size at some point in the future. It might just increase the payload size which will eventually run up against the API payload limit if the number of logcat lines is too high.
