### ISSUE TITLE
[Android] Falling back to sl4j logger

### ISSUE THREAD

**Issue by colinrtwhite** [rollbar/rollbar-java#174]
Seeing this warning for each submodule in our build:

`Could not get logger for '[module-name]'. Falling back to sl4j logger`

It appears to be related to sl4j, which the Rollbar SDK uses as a dependency.

We're currently using Rollbar SDK v1.3.1.

**Comment by jessewgibbs** [comment]
@colinrtwhite sorry for the problems and thanks for reporting this issue.

@rokob @basoko any suggestions for how to troubleshoot this?

**Comment by colinrtwhite** [comment]
Any update on this?

**Comment by rokob** [comment]
Is this just a warning or does this prevent the code from compiling/running?

Is it this warning:
> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

If not that one, is it exactly what you put in the initial comment or is that paraphrased? I can't seem to find anything that would generate that exact text so I'm not sure where to dig around for this.

**Comment by brianr** [comment]
Hey @colinrtwhite, it seems this is just a warning that doesn't affect functionality, and it appears there is not a straightforward way to avoid it, so we're going to close this for now. Let us know if this causes an issue for you that makes it worth more investigation.

**Comment by colinrtwhite** [comment]
Sorry for the late reply - the warning seems to have disappeared after upgrading to AGP `3.3.2` so it may have been a plugin issue.
