### ISSUE TITLE
Use an existing JSON library to generate JSON

### ISSUE THREAD

**Issue by marshallpierce** [rollbar/rollbar-java#18]
The existing by-hand JSON serialization, while workable, doesn't seem like it's adding a lot of value. A fair amount of code and complexity could be removed by using an existing mature JSON library like http://wiki.fasterxml.com/JacksonHome. Hopefully reporting exceptions isn't a frequent occurrence, but Jackson is also very fast.

If this is of interest I'm happy to contribute a PR.

**Comment by Crisfole** [comment]
We really didn't want to introduce an external dependency. Java has such a huge variety of JSON librariers out there that picking a single one didn't feel right. Serializing JSON is pretty simple and hard to get wrong. That functionality is extremely carefully tested too.

Feel free to improve on it, and feel free to add a module that *uses* Jackson to serialize, but we don't want the hard dependency if we don't have to have it. (Right now the code base is *pure* java, no dependencies except in testing).
