### ISSUE TITLE
Make RollbarFilter dependency-injectable for rollbar-web

### ISSUE THREAD

**Issue by ArturMoczulski** [rollbar/rollbar-java#182]
One of our users is programmatically constructing information usually contained in `web.xml`. In the proccess, they are initializing the Rollbar object before creating the RollbarFilter object. They want to be able to pass their already initialized Rollbar object to RollbarFilter.

Currently, this is functionality is only available inside `com.rollbar.web.filter` namespace due to the private constructor. We need to change the private constructor to publish to expose this functionality.

**Comment by simonyun** [comment]
thanks for the exceptional, prompt attention, @ArturMoczulski!
