### ISSUE TITLE
Make `RollbarAppender(Rollbar rollbar)` constructor public and allow `start()` to skip `Rollbar` instantiation so `RollbarAppender` can be constructed and started programmatically

### ISSUE THREAD

**Issue by simonyun** [rollbar/rollbar-java#184]
Similar to #182, I'd like to construct and start a `RollbarAppender` programmatically. As I see it, there are two things preventing this:
* I already have a `Rollbar` instance that I'd like to inject, but the constructor is package-private; making it public as in #182 would fix this.
* I'd need to call `RollbarAppender.start()` myself, so make that function skip `this.rollbar` instantiation if it already exists.

**Comment by simonyun** [comment]
@ArturMoczulski Any thoughts here? I can open a PR if that'd be helpful.

**Comment by ArturMoczulski** [comment]
Let me look into it

**Comment by ArturMoczulski** [comment]
If you know exactly what you need a PR would be most welcome

**Comment by simonyun** [comment]
All right, can do.
