### ISSUE TITLE
Release artifacts on Bintray for faster turnaround

### ISSUE THREAD

**Issue by marshallpierce** [rollbar/rollbar-java#19]
In my experience, releasing artifacts through maven central (via the Sonatype OSS process) is a slow process with multi-hour waits for artifacts to sync to mirrors. As a user, it would be nice to get new releases immediately when I'm eager to get a bug fix. Releasing on Bintray instead (which I have switching all of my projects) is *much* faster, and has other niceties as well (good CDN for distribution, etc). You can still have artifacts synced to maven central if you wish, or users can use the 'jcenter' repo, which is a superset of maven central, with the aforementioned CDN, etc.

If this sounds good, I'll make a PR.

**Comment by Crisfole** [comment]
It does take a long time...yes, but it's also *the* standard (unless I'm misunderstanding something). A fix that released to both would be welcome.

**Comment by marshallpierce** [comment]
Closing per comments in #21
