### ISSUE TITLE
Find way to not overwrite code_version when using different pro guard mapping files

### ISSUE THREAD

**Issue by letaniaferreira** [rollbar/rollbar-java#191]
We have a bunch of cloned apps,if we use same the versionName, it's gonna overwrite each other and eventually there would be only one mapping file 

https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/488687/conversations/22950492934

**Comment by basoko** [comment]
I think `code_version` can be set from notifier's configuration, so it can be customized to the specific needs of each cloned app.
