### ISSUE TITLE
Method in request builder

### ISSUE THREAD

**Issue by cristiammercado** [rollbar/rollbar-java#195]
Hi,

First of all, thank you very much for excellent work with this library.

I've detected a problem with the `Request Builder` ([see here](https://github.com/rollbar/rollbar-java/blob/master/rollbar-api/src/main/java/com/rollbar/api/payload/data/Request.java)). At the moment of using the Request Builder, the `method` value setted is not being sent to the Rollbar API. 

I think the error may be in [this function](https://github.com/rollbar/rollbar-java/blob/master/rollbar-api/src/main/java/com/rollbar/api/payload/data/Request.java#L130), where the value of the `method` variable is completely ignored.

Code example:

```java
Provider<Request> requestProvider = () -> new Request.Builder()
            .url("http://www.example.com?page=1")
            .method("GET")
            .queryString("page=1")
            .userIp("127.0.0.1")
            .build();

Config config = ConfigBuilder.withAccessToken("serverapikeyhere")
            .request(requestProvider)
            .build();

Rollbar instance = Rollbar.init(config);

instance.error(anyThrowable, "any message");
```

JSON after item was created in Rollbar:

```javascript
{
"request": {
    "user_ip": "127.0.0.1",
    "url": "http://www.example.com?page=1",
    "query_string": "page=1"
  }
}
```

Thanks in advance.

**Comment by basoko** [comment]
Hi @cristiammercado !

I'm very sorry for the late response about this. We have release a fix for this in the 1.7.3 version.

Thanks!
