### ISSUE TITLE
Avoid using subclassing as a means of customization

### ISSUE THREAD

**Issue by marshallpierce** [rollbar/rollbar-java#20]
The `com.rollbar.Rollbar` class suggests subclassing to allow for customizing things dynamically. This is clumsy in practice as it would be forced to rely on thread locals and the like. It would be easier to use if the context for a report could be provided per-call as an object.

Like all the other issues, happy to provide a PR.

**Comment by Crisfole** [comment]
Can you link to the docs? Everywhere I could I used interfaces that could be replaced with custom stuff to prevent this exact issue. I'm not sure I follow

**Comment by marshallpierce** [comment]
I'm just going off of the header of Rollbar.java:

https://github.com/rollbar/rollbar-java/blob/master/rollbar/src/main/java/com/rollbar/Rollbar.java#L17

**Comment by dlsteuer** [comment]
@marshallpierce did you have a particular use case for this, where you were trying to accomplish something?

**Comment by marshallpierce** [comment]
I wanted to add context at the point the error occurred. I rewrote the java client to be more suitable for my usecase (nonblocking, and more customizable) at https://github.com/truevault/rollbar-java so you can close this if you want.
