### ISSUE TITLE
Use Gradle as the build system

### ISSUE THREAD

**Issue by marshallpierce** [rollbar/rollbar-java#21]
Not sure how open you are to changing build systems after all the other stuff I've offered to swap out, but Gradle is pretty radically superior to Maven:
- It's faster (most builds speed up when converted to the equivalent Gradle build)
- It's more reliable (if you haven't fallen afoul of Maven's dependency resolution inconsistencies, you will)
- It's parallel-friendly (parallel builds have been a thing for a long time, and its downloaded artifact cache is safe to use concurrently, unlike Maven's)
- It's way more flexible when you need to do custom stuff
- There's nothing to install, ever: the build tool version and bootstrap is embedded in the project, so there's never "it works on my machine" because of different build tool versions. This also makes it really easy to use in CI.
- It's well supported in IntelliJ and Eclipse

And of course, I'll PR this as well if you want.

**Comment by Crisfole** [comment]
I'm open to a PR! I chose maven because it seemed to be pretty global, and because I assumed it meant deploying to maven central was easier. I'm happy to be proven wrong.

**Comment by marshallpierce** [comment]
Based on the other issues I've filed it sounds like you want to go a different direction than what I need for my integration, so I'm going to have a perma-fork here: https://github.com/truevault/rollbar-java

I'll do all the stuff I've described there, starting with this so that it's easy for you to borrow.
