### ISSUE TITLE
Documentation issues for rollbar-android

### ISSUE THREAD

**Issue by baz8080** [rollbar/rollbar-java#247]
Hi, I'm evaluating Rollbar for Mobile, and I've run into many issues with inconsistent documentation during on-boarding. I think it really would hurt adoption if left unfixed.

When the onboarding flow is followed, I select Android, and ultimately see this screen:

![onboard](https://user-images.githubusercontent.com/1534413/109168380-abf8fd00-7776-11eb-8413-f8ed3b4458df.png)

Some of the issues here include:

* Using `compile` rather than `implementation`. `compile` has been deprecated for a long time.
* Using an out of date version in the gradle snippet.  I'm using 1.7.5, which is a lot newer than the beta version you display. 

Then if you follow the docs to https://{my rollbar instance}.com/docs/notifier/rollbar-java/#android or https://{my rollbar instance}.com/docs/notifier/rollbar-android/you'll notice that there is no anchor section for Android. If I Google I can see this page: https://docs.rollbar.com/docs/android, which at least mentions `rollbar-android`, but lists an `1.+` version, which is frowned upon.

The bigger problem is that the docs say to use `<meta-data android:name="com.rollbar.android.POST_CLIENT_ACCESS_TOKEN"`. This wasn't working, so I debugged, and discovered your SDK is actually set up to look for `<meta-data android:name="com.rollbar.android.ACCESS_TOKEN"` instead.

Thanks!

**Comment by diegov** [comment]
Hi @baz8080, thanks for the detailed report. 

The onboarding documentation on the on-prem instance you're using is out of date, so I will investigate what can be done about that. 

The token issue in docs.rollbar.com will be fixed soon. 

As for the dependency version, you're right that `1.+` is not a good practice, unfortunately those docs are not automatically updated on new releases, and the goal is for the documentation to be straight forward and not full of caveats / side notes / detours (eg. ideally we'd avoid "now go to maven central, check for the latest version, and come back to continue.")
We have to think about it a bit to find the right balance between best practices, keeping things up to date, and avoiding manual release work. 

I will keep this open and update on the progress. 

Thanks,
Diego

**Comment by diegov** [comment]
Hi @baz8080, we've made a few changes to the documentation on https://docs.rollbar.com/docs/android to address the issues you mention. 

For the documentation embedded into you Rollbar instance, it is not possible to update them separately, so they will be automatically brought up to date the next time your instance is updated. 

Thanks!
Diego
