### ISSUE TITLE
rollbar does not seem to show items

### ISSUE THREAD

**Issue by RobiFerentz** [rollbar/rollbar-java#25]
I'm attempting to use this library in an Openfire XMPP server plugin.

My setup is like this:
`public static final Rollbar rollbar = new Rollbar("myaccesstokenblahblah", "development");`

Later in the code I use it like so:

`rollbar.debug("Bot sent message");`

It seems to be sending something to api.rollbar.com (at least according to Wireshark, which is very hard to read), but nothing appears on the items list on the rollbar UI.

Could this be an issue with my code? My rollbar account settings? The java code itself?
I'm stumped.

**Comment by dlsteuer** [comment]
Hey there @RobiFerentz sorry for the delay in responding to you, can you email your user name to support@rollbar.com or contact me via in-app intercom, and I can dig into what's going on here, the code should be working with that simple test case.

**Comment by RobiFerentz** [comment]
This was an issue with a malformed API key. Closing.
