### ISSUE TITLE
API error: Invalid format. data.body

### ISSUE THREAD

**Issue by TheMaskedMonkey** [rollbar/rollbar-java#27]
> API error: Invalid format. data.body must have either a 'trace', 'trace_chain', 'message' or 'crash_report' property, (but not more than one).

No idea why this is happening,

All I did was add `public static final Rollbar rollbar = new Rollbar("KEY", "production");`
to the top of my start file and added `rollbar.handleUncaughtErrors();` at the of the main void.

Any ideas?

**Comment by dlsteuer** [comment]
hey there @TheMaskedMonkey can you email your username into support@rollbar.com and I can dig into what's going on here with you?

**Comment by TheMaskedMonkey** [comment]
Hi, I emailed you :)

**Comment by dlsteuer** [comment]
Thanks for the bug report, this will be fixed in #28
