### ISSUE TITLE
Log4j2 examples are missing enabled parameter, leading to disabled rollbar integration

### ISSUE THREAD

**Issue by st-h** [rollbar/rollbar-java#270]
I just discovered that the log4j2 docs are missing some crucial configuration, which leads to rollbar not reporting any errors at all.

An additional parameter `enabled` has been added to the log4j2 config, which seems to be `false` per default ( https://github.com/rollbar/rollbar-java/commit/d619d028cfb22a461525ecb81db09c0029cffd06 ).

Unless this property is explicitly enabled, one never receives any rollbar messages.

This parameter should either be added to the examples or the enabled parameter should have a default value of `true`, so that rollbar is enabled unless it is explicitly disabled. 

I had to set logging to `debug`, then rollbar logs that it is disabled. Looking through the source, I found that there are more parameters than mentioned in the docs.

**Comment by diegov** [comment]
Hi @st-h, thanks for the report. 

We will make sure the docs are up to date, but for the `enabled` parameter specifically, it should be set to true by default as you mention, so no additional config should be necessary in documentation or examples. 

We will release a new version today which includes the fix.
