### ISSUE TITLE
rollbar-java

### ISSUE THREAD

**Issue by Mawlamyaigyun** [rollbar/rollbar-java#275]
import com.rollbar.android.Rollbar

public class MainActivity extends AppCompatActivity {

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    Rollbar.init(this);
    Rollbar.instance().error(new Exception("This is a test error")); //remove this after initial testing
  }
}

**Comment by diegov** [comment]
Hi @Mawlamyaigyun, this issue looks like it was created accidentally. If not, could you please add more details to it?

**Comment by diegov** [comment]
Closing due to lack of feedback.
