### ISSUE TITLE
Support for Spring Boot 3.x

### ISSUE THREAD

**Issue by nothing-personal-gh** [rollbar/rollbar-java#300]
The latest version 1.9.0 is still depending on Spring Boot 1.4.2 while 3.0.0 is out. This version doesn't compile with Spring Boot 3.0.0.

```
Caused by: java.lang.AbstractMethodError: Receiver class com.rollbar.spring.boot.webmvc.RollbarServletContextInitializer does not define or inherit an implementation of the resolved method 'abstract void onStartup(jakarta.servlet.ServletContext)' of interface org.springframework.boot.web.servlet.ServletContextInitializer.
```

All javax.servlet.* imports have to be replaced with `jakarta.servlet.*`

**Comment by cyrusradfar** [comment]
Appreciate that heads up. We can remedy this.

**Comment by beetlegius** [comment]
Any update? :)

**Comment by lbkulinski** [comment]
Hello! Any update on this? Thanks!

**Comment by cyrusradfar** [comment]
Hi. Appreciate your patience as the contributors who would work on this have were offline since soon after our last post. We're starting the upgrade in the upcoming sprint starting Jan 17th so it will be tested and released before the end of Feb or sooner if there are no issues.

**Comment by lbkulinski** [comment]
@cyrusradfar Thanks for the update!

**Comment by lbkulinski** [comment]
@cyrusradfar If you need any external testing for this, I'd be more than happy to help. Thanks again!

**Comment by lbkulinski** [comment]
Hello. Is there any update on this? Thank you!

**Comment by rollbar-bborsits** [comment]
Hey @lbkulinski, We're actively working on this issue currently. If no blocker pops up, you can expect a release in the following weeks at the latest.

**Comment by rollbar-bborsits** [comment]
@lbkulinski @beetlegius @nothing-personal-gh We released a [new Java SDK version](https://github.com/rollbar/rollbar-java/releases/tag/v1.10.0) that supports Spring 6.x and Spring Boot 3.x.
Let me know if you need any help with the upgrade. You can find the [docs here](https://docs.rollbar.com/docs/spring).

**Comment by lbkulinski** [comment]
@rollbar-bborsits Thanks! This is working well for me. I added it to two projects over the weekend.
