### ISSUE TITLE
Feature request: support for Spring WebFlux and Spring Boot 3.x

### ISSUE THREAD

**Issue by matsev** [rollbar/rollbar-java#305]
Please add support for facilitating bootstrapping of Rollbar using Spring Webflux and Spring Boot 3.x.

According to the [Rollbar changelog](https://github.com/rollbar/rollbar-java/blob/master/CHANGELOG.md), support for Spring 6.x and Spring Boot 3.x was added as part of version 1.10.0. Additionally, `rollbar-reactive-streams` and `rollbar-reactive-streams-reactor` was released as part of version 1.9.0. However, it seems there is currently no support for the union Spring WebFlux and Spring Boot 3.x?

One observation is that the `RollbarServletContextInitializer` provided by the `rollbar-spring-boot3-webmvc` library adds a `RollbarRequestListener` to the `ServletContext`. This needs to be ported as there is no servlet context in the reactive world.

Another observation is that Rollbar `rollbar-reactive-streams` has its own `AsyncHttpClient` interface with two different implementations. In contrast, the WebFlux [WebClient](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/reactive/function/client/WebClient.html) can be backed by [several different http clients](https://docs.spring.io/spring-framework/reference/web/webflux-webclient.html). Ideally, Rollbar would pick any `WebClient` bean available in the application context or delegate to Spring for creation of a new one.

**Comment by rollbar-bborsits** [comment]
@matsev What's the minimum version of Java and Spring you want to work with?

**Comment by matsev** [comment]
The project that I am currently working on is based on Java 17 and Spring Boot 3.1.1. Going forward, this project aims to upgrade with Java LTS versions when they become available in addition to upgrading Spring Boot releases when they become available.

Spring Boot 3.x is based on Spring Framework 6.x and it's wiki page has a [list of supported JDK versions](https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Versions#jdk-version-range):
- Spring Framework 6.1.x: JDK 17-23
- Spring Framework 6.0.x: JDK 17-21

The Spring Framework 6 release includes several breaking changes compared to the 5.x release. Copied from [What's New in Version 6.0](https://github.com/spring-projects/spring-framework/wiki/What's-New-in-Spring-Framework-6.x#whats-new-in-version-60):
- JDK 17+ and Jakarta EE 9+ Baseline
- Entire framework codebase based on Java 17 source code level now.
- Migration from javax to jakarta namespace for Servlet, JPA, etc.
- Runtime compatibility with Jakarta EE 9 as well as Jakarta EE 10 APIs.
- Compatible with latest web servers: [Tomcat 10.1](https://tomcat.apache.org/whichversion.html), [Jetty 11](https://www.eclipse.org/jetty/download.php), [Undertow 2.3](https://github.com/undertow-io/undertow).
- Early compatibility with [virtual threads](https://spring.io/blog/2022/10/11/embracing-virtual-threads) (in preview as of JDK 19).

Additionally, Spring Boot 3 also has upgraded many other third party dependencies as mentioned in the [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Release-Notes#third-party-library-upgrades). For specific details about currently used versions, please refer to the [spring-boot-dependencies](https://central.sonatype.com/artifact/org.springframework.boot/spring-boot-dependencies/3.1.1) pom file.

**Comment by rollbar-bborsits** [comment]
@matsev Thanks for sharing. I'll bring this back to the devs.

**Comment by matsev** [comment]
@rollbar-bborsits thanks for your feedback. Based on your reply, I created a follow up ticket in which I suggest that you revisit the documentation of the `rollbar-reactive-streams-reactor` usage, please see #307 for details.
