### ISSUE TITLE
Incorrect class names in stack traces

### ISSUE THREAD

**Issue by mabn** [rollbar/rollbar-java#34]
Clients based on ahaid/rollbar-logback send "class_name" in the stack trace elements, e.g.:

```
          {
            "class_name": "java.lang.Thread", 
            "method": "run", 
            "lineno": 745, 
            "filename": "Thread.java"
          }, 
          {
            "class_name": "org.eclipse.jetty.util.thread.QueuedThreadPool$3", 
            "method": "run", 
            "lineno": 540, 
            "filename": "QueuedThreadPool.java"
          }, 
          {
            "class_name": "org.eclipse.jetty.util.thread.QueuedThreadPool", 
            "method": "runJob", 
            "lineno": 620, 
            "filename": "QueuedThreadPool.java"
          },
```

which results in a more java-like stacktrace on the UI:

```
128 at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob (QueuedThreadPool.java:620)
129 at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run (QueuedThreadPool.java:540)
130 at java.lang.Thread.run (Thread.java:745)
```

On the other hand this library does not support _class_name_ and sends Frame objects without this field, which is rendered on the UI like this:

```
128 at runJob (org.eclipse.jetty.util.thread.QueuedThreadPool.java:620)
129 at run (org.eclipse.jetty.util.thread.QueuedThreadPool$3.java:540)
130 at main ( java.lang.Thread.java:745)
```

It's a bit odd given that the file names are incorrect (especially that ...$3.java)

Rollbar API spec does not mention _class_name_. 

Could _class_name_ be included (in the spec and in this client) to make stack traces in the UI look like regular java stacktraces - same as the ones from ahaid/rollbar-logback?

**Comment by mattdrees** [comment]
I see that the api spec has a 'class_name' field in the `frames[].context` object. Is this the appropriate place to put the stack frame class name? Will it render a java-like stacktrace in the rollbar UI?

**Comment by mattdrees** [comment]
The answer to my question is 'No'. The `context.class_name` field seems to be ignored by the UI.

**Comment by brianr** [comment]
Hi @mattdrees - Rollbar staff here... the `class_name` goes in `frames[].class_name`, not nested inside `context`. Looks like the api docs have that wrong - apologies; will update!

**Comment by mattdrees** [comment]
Gotcha; that makes more sense. Thanks Brian.

**Comment by mattdrees** [comment]
I'm working on a PR to add support for this to rollbar-java.
