### ISSUE TITLE
language does not default to java if unspecified, despite javadoc

### ISSUE THREAD

**Issue by janeklb** [rollbar/rollbar-java#35]
`Rollbar rollbar = new Rollbar("key", "env")` leaves `rollbar.getLanguage() == null`, despite constructor javadoc indicating that language would default to "java". Conversely, `rollbar.getFramework().equals("java")` instead.

**Comment by janeklb** [comment]
@rokob if you're able to say: what dictates the icon that appears next to a rollbar item (on the rollbar.com dashboard)? My JS errors are showing up with an 'html5 badge', but my java exceptions have no icon at all, even though I'm constructing my `Rollbar` with `setLanguage("java")`.

**Comment by rokob** [comment]
The icon currently only uses the value of the framework value, however for whatever reason there is not an icon for java. I've filed an internal task to rectify this.

**Comment by janeklb** [comment]
@rokob thanks, good to know that this is what drives the icon. Do you have a list of icon-supported values for that field?
