### ISSUE TITLE
Play framework

### ISSUE THREAD

**Issue by jessewgibbs** [rollbar/rollbar-java#47]
Details in https://app.clubhouse.io/rollbar/story/3531/play-framework

**Comment by aistomin** [comment]
@jessewgibbs the link you've posted is not public, it requires to login.

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
