### ISSUE TITLE
Fallback to simple String serialization for custom data types

### ISSUE THREAD

**Issue by sbilinski** [rollbar/rollbar-java#48]
I found some room for improvement in [RollbarSerializer](https://github.com/rollbar/rollbar-java/blob/32a154f0676db70b2f327e28f06d015baad89c0e/rollbar-utilities/src/main/java/com/rollbar/utilities/RollbarSerializer.java#L60) (version `0.5.4`). Consider the following **Scala** code as an example:

```
val customData = Map(
  "customParam" -> Some("hello world") //String -> scala.Option[String]
)

val customDataJava = customData.mapValues(_.asInstanceOf[AnyRef]).asJava //java.util.Map<String, Object>

rollbar.error(new RuntimeException("Some error"), customDataJava)
```

The JSON payload will have the following format in this case: 
```
{  
   ...
   "data":{  
      ...      
      "custom":{  
         "customParam": //No value here
      },
      "notifier":{  
         "name":"rollbar",
         "version":"0.5.4"
      }
   }
}
```

...which will result in a `BadRequest` status and a `could not parse json` message. 

I think this could be improved by sending a `toString()` value when all other options are exhausted [here](https://github.com/rollbar/rollbar-java/blob/32a154f0676db70b2f327e28f06d015baad89c0e/rollbar-utilities/src/main/java/com/rollbar/utilities/RollbarSerializer.java#L85). 

I'll gladly open a PR for this, if this kind of behaviour would be acceptable for you.

**Comment by aistomin** [comment]
@sbilinski yes, I also proposed it there: #42

**Comment by sbilinski** [comment]
@aistomin I just browsed the open issues, but didn't notice your PR - sounds awesome! I'll leave the  issue open for visibility in this case.

**Comment by rokob** [comment]
Merged
