### ISSUE TITLE
Basic construction of Rollbar throws a NullPointerException

### ISSUE THREAD

**Issue by berlin-ab** [rollbar/rollbar-java#5]
I created a pull request that contains a test to drive out a fix, but I am not sure which direction you'd prefer the fix to go.  Should the constructor include another required argument, or should the construction of the object be more defensive?

https://github.com/rollbar/rollbar-java/pull/4

**Comment by Crisfole** [comment]
Go ahead and fix the constructor.  I have a fix for this that I apparently never pushed. I'll let you fix, though.

As a rule I prefer making methods/constructors work as is.

Closing this in favor of #4
