### ISSUE TITLE
Readme updates for Getting Started

### ISSUE THREAD

**Issue by berlin-ab** [rollbar/rollbar-java#6]
I expected to see an example of how to use the library at the top of the readme. I usually find the usage and installation to be the most important information for new users.  People interested in contributing (like myself) will read further down the readme for information on how the project is structured and how we can contribute.

Do you have any preferences on what an example snippet should look like?

**Comment by Crisfole** [comment]
Hey Adam, The `Rollbar` module is the way to go for getting started.

Ultimately I envision a pile of small modules that integrate with your app via log4j, logback, or other similar tools.

**Comment by berlin-ab** [comment]
Maybe the https://github.com/rollbar/rollbar-java could point new users in the right direction then? I found the rollbar module's readme on accident when I tried to go digging through the source code for examples.
