### ISSUE TITLE
0.5.0 is marked as a release in Github but is not released on Maven 

### ISSUE THREAD

**Issue by berlin-ab** [rollbar/rollbar-java#7]
http://search.maven.org/#search%7Cga%7C1%7Crollbar

0.4.0 is the latest available for download.

**Comment by Crisfole** [comment]
Oops! Good catch. It must be because I need to request OSSRH to add the new artifacts...I'd have thought once the group was up that we could push any artifacts...

**Comment by Crisfole** [comment]
https://oss.sonatype.org/content/groups/public/com/rollbar/rollbar/0.5.0/
