### ISSUE TITLE
Documentation for api 1.0.0-beta-1

### ISSUE THREAD

**Issue by helderribeirosousa** [rollbar/rollbar-java#72]
I've seen you've added my previous issue (#67) to the changelog for the 1.0.0-beta-1 version. Thank you.
Now i've updated to that version but now NONE of my issues are being sent to rollbar!

I mean... Where's the javadoc for the 1.0.0-beta-1 version?
I'm using this code...

`public static final Rollbar rollbar = new Rollbar(withAccessToken("ACCESS_TOKEN").environment("production").build());

Map<String,Object> custom = new HashMap<>();
custom.put("fingerprint",code);
custom.put("message",message);

rollbar.critical(myThrowable,custom);`

This is supposed to send the payload to rollbar right?
Seriously guys... I need to have this on components that are being used in production ASAP.
And let's pretend that i'm not actually having to resort to a beta build in such environments in the first place.

**Comment by rokob** [comment]
1. There was an issue uploading the javadocs, I am going to publish 1.0.0-beta-2 with the javadocs right now.
2. When you say NONE of your issues are being sent to rollbar, what exactly is happening? The code snippet you provided is compiling, running without throwing an exception, but nothing is showing up in the UI? Or some other scenario?

The code snippet you put there should indeed send the payload to rollbar.

**Comment by helderribeirosousa** [comment]
Ok. I finally had some time to test all my components with the 1.0.0-beta-1. I have three of them and two of them are working fine. The one that is not working is actually the one that caused me to open issue #67.

Here's how i'm initializing rollbar and submiting an error:
https://pastebin.com/NPz1SdD4

Here's a stacktrace that is not being sent:
https://pastebin.com/b7nqEfey

Maybe you should throw an Exception whenever an error could not be sent to rollbar.
That way i could catch it and know it wasn't sent. I could also see in which part of your code the exception was thrown.

**Comment by basoko** [comment]
I think you could monitor it attaching an event listener to the `Sender`. I leave a piece of code to show you how you can do it.

```

**Comment by helderribeirosousa** [comment]
Here it is! 

**Error: com.rollbar.notifier.sender.exception.SenderException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target**

Thanks to this i was able to figure out what was causing the issue. I've replaced java's trustStore by a local store file and that was causing an ssl handshake error (couldn't validate your certificate's chain).
I've removed the code that was pointing to my local file and added those keys to the Java's default keystore ("$(JDK_INSTALL)/jre/lib/security/cacerts") using Java's keytool.
Now everything is fine.

I really think you should throw an exception whenever a payload isn't sent.

Anyway, thank you very much for your help on finding the issue.

**Comment by brianr** [comment]
@helderribeirosousa glad you were able to fix the problem, and thanks for following up!

I've filed #76 to track changes related to making this kind of thing easier to find.
