### ISSUE TITLE
Improve troubleshooting for SSL cert issues

### ISSUE THREAD

**Issue by brianr** [rollbar/rollbar-java#76]
The problem @helderribeirosousa had in #72 is going to come up again for more users. Let's figure out some ways to make this issue, and other issues that manifest just as "it doesn't work", easier to debug and fix.

For the SSL cert issue in particular, we should add some documentation.

**Comment by basoko** [comment]
I think we could add some logging traces to report information about the processing status. We could do that using a logging facade like slf4j, that will allow clients to plug-in they preferred logging system in their applications.
