### ISSUE TITLE
Publish rollbar-android so that it includes dependencies

### ISSUE THREAD

**Issue by rokob** [rollbar/rollbar-java#78]
Right now to work with rollbar-android you need to use

```
compile('com.rollbar:rollbar-android:1.0.0-beta-2@aar'){transitive=true}
```

Because of the way the packages are published. It should just work with

```
compile('com.rollbar:rollbar-android:1.0.0-beta-2')
```

Fix the packaging and publishing to make that true.

**Comment by woohoou** [comment]
+1

**Comment by petitJAM** [comment]
Any word on a fix for this?  I'm currently reverting back to 0.2.1 because I cannot make release builds with 
```
compile('com.rollbar:rollbar-android:1.0.0-beta-2@aar'){transitive=true}
```

**Comment by rokob** [comment]
Can you describe more what is actually happening with that dependency specification? If you use

```
compile('com.rollbar:rollbar-api:1.0.0-beta-2')
compile('com.rollbar:rollbar-java:1.0.0-beta-2')
compile('com.rollbar:rollbar-android:1.0.0-beta-2@aar')
```

without the transitive part, then things should work. The transitive part is meant to pick up those other dependencies with the `@aar` part. I haven't been able to resolve this otherwise, but if you can give me a stack trace or some other kind of error output that comes from using `...@aar'){transitive=true}` it would be quite useful.

**Comment by colinrtwhite** [comment]
Any word on the `1.0.1` release? :)

**Comment by rivkahstandig3636** [comment]
@colinrtwhite Planned in the next few weeks!

**Comment by rivkahstandig3636** [comment]
@petitJAM Did you see @rokob's comment?

**Comment by petitJAM** [comment]
I did, but I didn't get a chance to go back and try it out again and then I kinda forgot about it :/

**Comment by basoko** [comment]
Version 1.3.0 should publish correctly the dependencies
