### ISSUE TITLE
rollbar-java StaticLoggerBinder

### ISSUE THREAD

**Issue by 7wonders** [rollbar/rollbar-java#85]
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Comment by mattdrees** [comment]
If anything, I'd suggest that this is only a documentation problem. `rollbar-java` should not be providing the logger implementation; the client app should. The readme should clarify that the app should make sure an slf4j logger implementation is on the classpath.

**Comment by rivkahstandig3636** [comment]
@rokob What do you think?

**Comment by rokob** [comment]
This is just a documentation issue

**Comment by basoko** [comment]
Hi @mauricegavin ,

That warning is raised because `slf4j` doesn't find any `org.slf4j.impl.StaticLoggerBinder`, so it defaults to no-operation mode.
If you want to get rid of it, you should provide the appropriate binding of `slf4j` for the logging system that you use in you application, or if you don't want logging just provide the `slf4j-nop` binding.

**Comment by jaredanderton** [comment]
I was able to get this working by upgrading Kotlin and Gradle: 
(I think this is all I did - Sorry, I'm not an Android developer)
```buildscript {
     ext.kotlin_version = '1.2.71' // removed this
    ext.kotlin_version = '1.3.10' // added this
    ...
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1' // removed this
        classpath 'com.android.tools.build:gradle:3.5.3' // added this
 ```

**Comment by bennadel** [comment]
@jaredanderton your comment saved my bacon! I just spent the last 3-hours trying to figure out why I was having class-loading problems. I kept trying different loader configuration to no luck. Finally, including the `nop` JAR magically removed my issue!
