### ISSUE TITLE
support additional attributes for various objects in Payload

### ISSUE THREAD

**Issue by mattdrees** [rollbar/rollbar-java#86]
The [API docs](https://rollbar.com/docs/api/items_post/) are pretty clear that it's ok to send non-standard attributes in the item JSON, but rollbar-java 1.0.0 has removed this capability. (It could be done for some, but not all, objects in 0.5.4.)

Would you consider re-adding this capability?
I find it useful to record things like the response code, the timestamps at the beginning and the end of the request, extra person attributes, etc.

I'm sorry I wasn't able to get this feedback to you before 1.0.0 was released!

**Comment by rokob** [comment]
I assume you mean for the objects where we say:

> // Can contain any arbitrary keys. Rollbar understands the following:

Yeah we should add this back, will figure out the best way to do this.

**Comment by mattdrees** [comment]
Yes, that's what I meant.
Thank you!

**Comment by mattdrees** [comment]
So, actually, I'd prefer if additional attributes could be sent for Person, in addition to the ones marked by the 'arbitrary keys' comment. The rollbar UI didn't do anything with these attributes, but I could use them in RQL (IIRC).

Perhaps the spec can be amended to allow these on Person?

**Comment by rivkahstandig3636** [comment]
We should allow these on Person, I agree.
