### ISSUE TITLE
use unix timestamp instead of java timestamp

### ISSUE THREAD

**Issue by mattdrees** [rollbar/rollbar-java#88]
The API describes the `timestamp` field as a unix timestamp. However, `rollbar-java`'s default TimestampProvider provides a "java" timestamp, which is based on milliseconds instead of seconds. 

The rollbar UI doesn't seem to interpret this:
<img width="376" alt="screen shot 2017-11-27 at 12 58 46 pm" src="https://user-images.githubusercontent.com/58439/33286503-be37b3ae-d372-11e7-9bad-b8798d990d88.png">

I dislike how the api loses milliseconds, but it's probably best to be spec-compliant and divide the java timestamp by 1000 to dump the milliseconds.

**Comment by brianr** [comment]
Good find @mattdrees. I think we can probably keep the milliseconds on the "Notifier Timestamp" if rollbar-java sends it as a float. I believe it'll display without milliseconds on that "Notifier Timestamp" line, but the original value will be available in the Raw JSON section.

**Comment by rokob** [comment]
@brianr is that true? The fix here is to just send the value as a float or should we divide by 1000 to match the spec here: https://rollbar.com/docs/api/items_post/

**Comment by brianr** [comment]
@rokob ah sorry, I meant "divide by 1000 and send as a float".

**Comment by rokob** [comment]
Ah okay yeah
