### ISSUE TITLE
perhaps use strings instead of arrays for query parameters when only one is present

### ISSUE THREAD

**Issue by mattdrees** [rollbar/rollbar-java#89]
`rollbar-java` uses a json array for each request parameter. Semantically this is correct, but it seems the rollbar UI renders the array as a String, which is kinda ugly:
<img width="455" alt="screen shot 2017-11-27 at 1 02 24 pm" src="https://user-images.githubusercontent.com/58439/33286646-41a14d9a-d373-11e7-875c-7f8bd9a4953f.png">

And I didn't check, but I'd guess RQL queries would need to have to use something like `WHERE request.get.foo = '["bar"]'`.

It'd be nicer if, when there is only one value for the parameter, the rollbar UI and RQL mechanism used a simple String instead of an array. Maybe rollbar could do this server-side, but if not, this can definitely be achieved client-side, here in rollbar-java. Some kind of post-processing step could replace lists (of length 1) with the list's single element, before sending the json off to the rollbar API.

**Comment by rivkahstandig3636** [comment]
Thanks for the suggestion @mattdrees! We'll take a look a decide which approach to take here.

**Comment by mattdrees** [comment]
Thanks Andrew!
