### ISSUE TITLE
Add ability to List and delete items

### ISSUE THREAD

**Issue by andrescanavesi** [rollbar/rollbar-java#97]
Would be great to list items by date and by any other filter (maybe log level).
Also allow deletion of items by id / list of ids.

**Comment by rivkahstandig3636** [comment]
Hi there, This looks more like a feature request for the Rollbar UI and API than one that is specific to rollbar-java. Thanks for the feedback!

**Comment by brianr** [comment]
@rivkahstandig3636 I think the request here is for wrappers around the Rollbar API endpoint to do search/list items, e.g. https://rollbar.com/docs/api/items/#list-all-items . @andrescanavesi is that what you're looking for here?
